"use client";

import { useMemo, useState } from "react";
import { Box, Typography } from "@mui/material";
import { Icon } from "@iconify/react";
import { TutorSurface } from "../shared/surfaces";
import type { TutorNote } from "@/lib/services/ai-tutor.service";

/**
 * What the learner kept: flashcards and notes from past sessions.
 *
 * The previous version rendered every item as a question with its answer printed underneath,
 * in one undifferentiated list. That fails at the panel's actual job. Most of these rows are
 * *flashcards* generated by the recap — a question and its answer — and showing both sides at
 * once removes the only thing a flashcard is for. It also mixed items from unrelated lessons
 * into one wall of text with no dates, no topics and no end.
 *
 * So: answers are hidden until asked for, items are grouped by the lesson they came from, and
 * the panel is bounded with an explicit way to see the rest. A note (a summary the tutor saved,
 * with no question) still shows its body immediately, because there is nothing to test.
 */

const VISIBLE_GROUPS = 3;

interface NoteGroup {
  topic: string;
  items: TutorNote[];
}

/** A flashcard has a question and an answer. A note is just a summary. */
function isFlashcard(note: TutorNote): boolean {
  return Boolean(note.answer?.trim());
}

export function NotesPanel({ notes }: { notes: TutorNote[] }) {
  const [revealed, setRevealed] = useState<Set<number>>(new Set());
  const [showAll, setShowAll] = useState(false);

  const groups = useMemo<NoteGroup[]>(() => {
    const byTopic = new Map<string, TutorNote[]>();
    for (const note of notes) {
      const key = note.topic?.trim() || "Other";
      const list = byTopic.get(key);
      if (list) list.push(note);
      else byTopic.set(key, [note]);
    }
    return Array.from(byTopic, ([topic, items]) => ({ topic, items }));
  }, [notes]);

  const toggle = (id: number) =>
    setRevealed((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  const revealGroup = (group: NoteGroup) =>
    setRevealed((prev) => {
      const next = new Set(prev);
      const allShown = group.items.every((i) => next.has(i.id));
      group.items.forEach((i) => (allShown ? next.delete(i.id) : next.add(i.id)));
      return next;
    });

  if (!notes.length) return null;

  const visible = showAll ? groups : groups.slice(0, VISIBLE_GROUPS);
  const hiddenCount = groups.length - visible.length;
  const cardCount = notes.filter(isFlashcard).length;

  return (
    <TutorSurface padded={false}>
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          gap: 1,
          px: { xs: 2, md: 2.5 },
          py: 1.5,
          borderBottom: "1px solid var(--border-default)",
        }}
      >
        <Icon
          icon="solar:cards-bold-duotone"
          width={18}
          style={{ color: "var(--ai-violet)" }}
        />
        <Typography sx={{ fontSize: "0.88rem", fontWeight: 600 }}>
          {cardCount > 0
            ? `${cardCount} flashcard${cardCount === 1 ? "" : "s"}`
            : `${notes.length} note${notes.length === 1 ? "" : "s"}`}
        </Typography>
        <Box sx={{ flex: 1 }} />
        {cardCount > 0 ? (
          <Typography sx={{ fontSize: "0.78rem", color: "var(--font-secondary)" }}>
            Tap a question to check yourself
          </Typography>
        ) : null}
      </Box>

      <Box>
        {visible.map((group, gi) => (
          <Box
            key={group.topic}
            sx={{ borderTop: gi === 0 ? "none" : "1px solid var(--border-default)" }}
          >
            {/* The lesson these came from. Without it, cards from three different sessions
                read as one undifferentiated list. */}
            <Box
              component="button"
              type="button"
              onClick={() => revealGroup(group)}
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 1,
                width: "100%",
                px: { xs: 2, md: 2.5 },
                pt: 1.75,
                pb: 1,
                border: "none",
                bgcolor: "transparent",
                fontFamily: "inherit",
                cursor: "pointer",
                textAlign: "left",
                "&:focus-visible": {
                  outline: "none",
                  boxShadow: "0 0 0 2px var(--card-bg), 0 0 0 4px var(--ai-violet)",
                },
              }}
            >
              <Typography
                sx={{
                  fontSize: "0.74rem",
                  fontWeight: 600,
                  letterSpacing: "0.08em",
                  textTransform: "uppercase",
                  color: "var(--font-secondary)",
                  '[dir="rtl"] &': { letterSpacing: "normal", textTransform: "none" },
                }}
              >
                {group.topic}
              </Typography>
              <Box
                sx={{
                  px: 0.85,
                  py: 0.1,
                  borderRadius: 9999,
                  bgcolor: "var(--surface, #f1f5f9)",
                  fontSize: "0.72rem",
                  fontWeight: 600,
                  color: "var(--font-secondary)",
                }}
              >
                {group.items.length}
              </Box>
              <Box sx={{ flex: 1 }} />
              <Typography
                sx={{ fontSize: "0.74rem", color: "var(--ai-violet)", fontWeight: 500 }}
              >
                {group.items.every((i) => revealed.has(i.id)) ? "Hide all" : "Show all"}
              </Typography>
            </Box>

            {group.items.map((note) => {
              const card = isFlashcard(note);
              const open = revealed.has(note.id) || !card;
              const body = card ? note.answer : note.summary;
              return (
                <Box
                  key={note.id}
                  component={card ? "button" : "div"}
                  type={card ? "button" : undefined}
                  onClick={card ? () => toggle(note.id) : undefined}
                  aria-expanded={card ? open : undefined}
                  sx={{
                    display: "block",
                    width: "100%",
                    textAlign: "left",
                    border: "none",
                    bgcolor: "transparent",
                    fontFamily: "inherit",
                    px: { xs: 2, md: 2.5 },
                    py: 1.25,
                    cursor: card ? "pointer" : "default",
                    transition: "background-color 140ms ease",
                    "&:hover": card ? { bgcolor: "var(--surface, #f8fafc)" } : {},
                    "&:focus-visible": {
                      outline: "none",
                      boxShadow: "0 0 0 2px var(--card-bg), 0 0 0 4px var(--ai-violet)",
                    },
                  }}
                >
                  <Box sx={{ display: "flex", gap: 1.25, alignItems: "flex-start" }}>
                    {card ? (
                      <Icon
                        icon={open ? "solar:eye-bold" : "solar:eye-closed-bold"}
                        width={15}
                        style={{
                          color: open ? "var(--ai-violet)" : "var(--font-secondary)",
                          flexShrink: 0,
                          marginTop: 3,
                        }}
                      />
                    ) : (
                      <Icon
                        icon="solar:bookmark-bold"
                        width={15}
                        style={{
                          color: "var(--font-secondary)",
                          flexShrink: 0,
                          marginTop: 3,
                        }}
                      />
                    )}
                    <Box sx={{ minWidth: 0, flex: 1 }}>
                      <Typography
                        sx={{
                          fontSize: "0.92rem",
                          fontWeight: 500,
                          lineHeight: 1.45,
                          color: "var(--font-primary)",
                        }}
                      >
                        {note.concept || note.prompt}
                      </Typography>
                      {open && body ? (
                        <Typography
                          sx={{
                            fontSize: "0.88rem",
                            lineHeight: 1.5,
                            color: "var(--font-secondary)",
                            mt: 0.5,
                            // The answer is the payoff, so it gets a rule rather than just
                            // being lighter text directly under the question.
                            pl: 1.25,
                            borderLeft: "2px solid",
                            borderColor: card
                              ? "color-mix(in srgb, var(--ai-violet) 45%, transparent)"
                              : "var(--border-default)",
                          }}
                        >
                          {body}
                        </Typography>
                      ) : card ? (
                        <Typography
                          sx={{
                            fontSize: "0.8rem",
                            color: "var(--font-secondary)",
                            mt: 0.25,
                            fontStyle: "italic",
                          }}
                        >
                          Answer hidden
                        </Typography>
                      ) : null}
                    </Box>
                  </Box>
                </Box>
              );
            })}
          </Box>
        ))}
      </Box>

      {hiddenCount > 0 ? (
        <Box
          component="button"
          type="button"
          onClick={() => setShowAll(true)}
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: 0.75,
            width: "100%",
            py: 1.5,
            borderTop: "1px solid var(--border-default)",
            border: "none",
            borderTopWidth: 1,
            borderTopStyle: "solid",
            bgcolor: "transparent",
            fontFamily: "inherit",
            fontSize: "0.85rem",
            fontWeight: 500,
            color: "var(--ai-violet)",
            cursor: "pointer",
            "&:hover": { bgcolor: "var(--surface, #f8fafc)" },
          }}
        >
          <Icon icon="mdi:chevron-down" width={17} />
          {hiddenCount} more {hiddenCount === 1 ? "topic" : "topics"}
        </Box>
      ) : null}
    </TutorSurface>
  );
}
