declare module 'date-fns' {
  export function format(date: Date | number, formatStr: string): string;
  export function parseISO(argument: string): Date;
  export function startOfDay(date: Date | number): Date;
  export function endOfDay(date: Date | number): Date;
  export function endOfToday(): Date;
  export function eachDayOfInterval(interval: { start: Date; end: Date }): Date[];
  export function isSameDay(dateLeft: Date | number, dateRight: Date | number): boolean;
  export function addDays(date: Date | number, amount: number): Date;
  export function subDays(date: Date | number, amount: number): Date;
  export function subMonths(date: Date | number, amount: number): Date;
  export function startOfWeek(date: Date | number, options?: { weekStartsOn?: number }): Date;
  export function endOfWeek(date: Date | number, options?: { weekStartsOn?: number }): Date;
  export function eachWeekOfInterval(interval: { start: Date; end: Date }, options?: { weekStartsOn?: number }): Date[];
  export function isSameWeek(dateLeft: Date | number, dateRight: Date | number, options?: { weekStartsOn?: number }): boolean;
  export function startOfMonth(date: Date | number): Date;
  export function endOfMonth(date: Date | number): Date;
  export function eachMonthOfInterval(interval: { start: Date; end: Date }): Date[];
  export function isSameMonth(dateLeft: Date | number, dateRight: Date | number): boolean;
  export function getDay(date: Date | number): number;
  export function getDate(date: Date | number): number;
  export function getMonth(date: Date | number): number;
  export function getYear(date: Date | number): number;
  export function differenceInDays(dateLeft: Date | number, dateRight: Date | number): number;
  export function differenceInHours(dateLeft: Date | number, dateRight: Date | number): number;
  export function differenceInMinutes(dateLeft: Date | number, dateRight: Date | number): number;
  export function differenceInSeconds(dateLeft: Date | number, dateRight: Date | number): number;
  export function addHours(date: Date | number, amount: number): Date;
  export function addMinutes(date: Date | number, amount: number): Date;
  export function addSeconds(date: Date | number, amount: number): Date;
  export function subHours(date: Date | number, amount: number): Date;
  export function subMinutes(date: Date | number, amount: number): Date;
  export function subSeconds(date: Date | number, amount: number): Date;
  export function isToday(date: Date | number): boolean;
  export function isYesterday(date: Date | number): boolean;
  export function isTomorrow(date: Date | number): boolean;
  export function isThisWeek(date: Date | number, options?: { weekStartsOn?: number }): boolean;
  export function isThisMonth(date: Date | number): boolean;
  export function isThisYear(date: Date | number): boolean;
  export function isValid(date: any): boolean;
  export function parse(dateString: string, formatString: string, referenceDate?: Date): Date;
  export function parseISO(argument: string): Date;
  export function toDate(argument: Date | number): Date;
  export function isBefore(date: Date | number, dateToCompare: Date | number): boolean;
} 